# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'SwiftProjectDemo' do
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Alamofire', '~> 1.3'
pod 'AlamofireObjectMapper', '~> 0.7'
end

target 'SwiftProjectDemoTests' do

end

